### ISSUE TITLE
Py object not found

### ISSUE THREAD

**Issue by sam-schorb** [shakfu/py-js#10]
Hi there, I hope I shouldn't have commented in the closed thread because my issue would definitely be classified as newbie question. I've checked the other threads but unless I don't think I've seen a solution to the issue I'm having.

I am just trying to get the Py external installed but having problems. I am getting this error in the Max console and the Py object appears in an orange box.

'py: py: No such object'

I am using a 2020 M1 Macbook. I have tried using several different released versions of your externals. I also built my own but none of them are working. PyJS seems to be loading fine although I've not experimented with it yet. I'm probably making some minor rookie error but some guidance would be much appreciated. Thank you!

**Comment by shakfu** [comment]
Thanks for starting a new thread which is better then commenting in a closed thread.

The error you received means that Max cannot find the external.

This is easily fixed.

Externals are installed in the `externals` directory of a [Max package](https://docs.cycling74.com/max8/vignettes/packages). Max Packages are installed in the `$HOME/Documents/Max 8/Packages` where $HOME is `/Users/<your-username>`

You can create a minimal max package in that directory by doing the following:
1. make a new directory in `$HOME/Documents/Max 8/Packages` call it `demo` for now.
2. In this `demo` directory create another directory called `externals`
3. Download the [arm64 externals](https://github.com/shakfu/py-js/releases/download/0.1/py-js-v0.1-arm64-py3.9.12-static.zip) from the Releases section. Unzip this archive and inside you will find `py.mxo` and `pyjs.mxo` bundles: these are the externals. You can copy these into the newly created `externals`  directory above in your demo package. So, for example, the path of the `py.mxo` externals should be `$HOME/Documents/Max 8/Packages/demo/externals/py.mxo`.
4. Open `Max 8` and create a new `[py]` object and it should not give errors.

If the above works for you then should be good to with the releases externals at least.

Note that the project repo itself is a package (with all the bells and whistles) so you can also use that, instead of the `demo package` above and copy the above externals into it `externals` directory. (Don't have two packages with the same named externals at the same time, of course).

If you would like to compile your own, then you should first try follow steps in the quickstart noting the following:
1. don't clone the repo to a path with spaces or directly into `$HOME/Documents/Max 8/Packages`. Clone it to a path without spaces.
2. run `make setup` inside the cloned repo directory after cloning to create symlink between the cloned directory and `$HOME/Documents/Max 8/Packages`
3. make sure you have all the dependencies installed (see the readme). You need `cmake` and xcode and the python package `cython` at minimum.
4. run `make` to build the externals locally.

**Comment by sam-schorb** [comment]
Hi there, 

Thank you so much for this very detailed reply. I am sorry to have asked such a simple question. I am aware of these steps and had tried to follow them but I have several Max 8/Packages folders for different installations of Max and had seemingly places the externals in the wrong one. I wouldn't have realised this without your advice so thank you.

This software is such a good idea I am really looking forward to using it. Thank you again for your time.

**Comment by shakfu** [comment]
Hi @sam-schorb, 

Happy that you were able to resolve your issue. Feel free to post another issue if you need additional help. My advice is to go through the patcher examples.

I'll close this issue since it looks like you got it working.
