### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by al-baum** [shakfu/py-js#17]
Hi,
Sorry, this is possibly not an issue, but in case.
I am a complete beginner at Python, but understand Max well enough. This project is great thanks) and seems exactly what I need.

I have a Python program that  import some modules in subfolder. When I run it form th command line the program runs fine, but when I load into the py object I get an error in Max:

py: [ERROR] (bob) execfile: ModuleNotFoundError("No module named 'utils'")

Utils is not the name of the module, rather the folder that contains the module.
Firat line of code is:
from utils.action.mymodule import prompt.

I tried settin pythonpath to the same folder as the main program but it does not seem to help

 I am on windows 11 
Max 8.6.2
Python 3.10.6

Any help will be welcome,
Best
Alain

**Comment by shakfu** [comment]
Hi @al-baum 

Thanks for writing about your import issues using the `py` external:

> I have a Python program that imports some modules in a subfolder. When I run it from the command line the program runs fine, but when I load into the `py` object I get an error in Max:
> 
> py: [ERROR] (bob) execfile: ModuleNotFoundError("No module named 'utils'")
> 
> Utils is not the name of the module, rather the folder that contains the module. First line of code is: `from utils.action.mymodule import prompt`.
> 
> I tried setting `pythonpath` to the same folder as the main program but it does not seem to help

Looks like you should use `import` rather than `load` in this case. You can also send a message to `py`: `import utils.action.mymodule.prompt as prompt`. Make sure `utils` is in or has been added to the pythonpath

It's worth understanding the difference between the `load <file.py>` message which is equivalent to the python command `exec(open("<file>").read())` where `<file>` is a file that is found in the Max search path from the `import ...` or `from ... import ...` python idiom which is also accepted by `py`.

If you want to use the typical `pythonpath` search mechanism then use `import`, if you don't care and have a unique filename somewhere in the Max search path use `load`. Examples of both are given in the `py.maxhelp` file.

**Comment by al-baum** [comment]
Hi Shakfu,
Thank you so much for your reply, specially since it is not directly to your py object. Very kind of you.
I will explore the route you suggest, and close this issue,
Best,
Alain
