### ISSUE TITLE
Compilation on Apple Silicon

### ISSUE THREAD

**Issue by wwerk** [shakfu/py-js#3]
Hi, great take with this package!
I tried recompiling the objects myself since I'm on ARM and the building script provided throws:

`~/GitHub/py-js/source/py/pyjs.c:5:10: fatal error: 'Python.h' file not found
#include <Python.h>
         ^~~~~~~~~~
1 error generated.
`

I also tried regenerating the build files using cmake -g Xcode which gives the following error:

`-- Updating Git Submodules
building on Git rev : 259e877
Git tag : pre-release0
Generating Info.plist
Generating: pymx
-- Min-Lib found
CMake Error at source/projects/pymx/CMakeLists.txt:10 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.
  Could not find a package configuration file provided by "pybind11" with any
  of the following names:
    pybind11Config.cmake
    pybind11-config.cmake
  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.
-- Configuring incomplete, errors occurred!
`

**Comment by shakfu** [comment]
I haven't yet compiled on Apple Silicon and it looks like you are trying to compile the `min-dev` external (read the README if this not intentional), but it looks like you don't have `pybind11` installed. 

You can try the following:

```
brew install pybind11
```

and

```
pip install pybind11
```

Also make sure to check the architecture specified in Xcode is compatible for `arm64` (which is included in the the standard setting for Xcode, I believe). See [this](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary), if this is unclear.

**Comment by wwerk** [comment]
Unfortunately even after installing pybind11 it seems like the issue if building via script persists.
I have tried compiling with both Xcode and CMake, I'm positive the architecture is set to universal (both ARM and intel), still both throw the same error:

`FAILED: ../externals/pymx.mxo/Contents/MacOS/pymx 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -mmacosx-version-min=10.11 -bundle -Wl,-headerpad_max_install_names @~/GitHub/py-js/source/min-api/script/../max-api/script/max-linker-flags.txt @~/GitHub/py-js/source/min-api/script/../max-api/script/msp-linker-flags.txt -o ../externals/pymx.mxo/Contents/MacOS/pymx source/projects/pymx/CMakeFiles/pymx.dir/pymx.cpp.o -F~GitHub/py-js/source/min-api/max-api/lib/mac -Wl,-rpath,~/miniforge3/lib  -framework  JitterAPI  ~/miniforge3/lib/libpython3.9.dylib && cd ~/GitHub/py-js/cmake-build-debug/source/projects/pymx && cp ~/GitHub/py-js/source/min-api/max-api/script/PkgInfo ~/GitHub/py-js/source/projects/pymx/../../../externals/pymx.mxo/Contents/PkgInfo
ld: warning: ignoring file ~/GitHub/py-js/source/min-api/max-api/lib/mac/JitterAPI.framework/JitterAPI, missing required architecture arm64 in file~/GitHub/py-js/source/min-api/max-api/lib/mac/JitterAPI.framework/JitterAPI (2 slices)
Undefined symbols for architecture arm64:
  "_jit_class_addattr", referenced from:
      c74::min::attribute<std::__1::vector<double, std::__1::allocator<double> >, (c74::min::threadsafe)0, c74::min::limit::none, (c74::min::allow_repetitions)2>::create(c74::max::t_class*, void* (*)(void*, ...), void* (*)(void*, ...), bool) in pymx.cpp.o
      c74::min::attribute<std::__1::vector<int, std::__1::allocator<int> >, (c74::min::threadsafe)0, c74::min::limit::none, (c74::min::allow_repetitions)2>::create(c74::max::t_class*, void* (*)(void*, ...), void* (*)(void*, ...), bool) in pymx.cpp.o
      c74::min::attribute<c74::min::symbol, (c74::min::threadsafe)0, c74::min::limit::none, (c74::min::allow_repetitions)2>::create(c74::max::t_class*, void* (*)(void*, ...), void* (*)(void*, ...), bool) in pymx.cpp.o
ld: symbol(s) not found for architecture arm64`

**Comment by shakfu** [comment]
My checkouts of `min-api` and `min-lib` dependencies (as git submodules) may be dated so suggest to try the following:

First update `min-api`

```
cd py-js/source/min-api
git checkout master
git pull
```

then update `min-lib`:

```
cd py-js/source/min-lib
git checkout master
git pull
```

Then try to compile again.

**Comment by wwerk** [comment]
After doing the above what I'm getting is an error caused by min-api, JitterAPI.framework to be specific.
It might be on cycling this time I suppose.

```[main] Building folder: py-js 
[build] Starting build
[proc] Executing command: ~/miniforge3/bin/cmake --build ~/GitHub/py-js/build --config Debug --target all -j 10 --
[build] Consolidate compiler generated dependencies of target pymx
[build] [  0%] Built target LIB
[build] [ 50%] Building CXX object source/projects/pymx/CMakeFiles/pymx.dir/pymx.cpp.o
[build] In file included from ~/GitHub/py-js/source/projects/pymx/pymx.cpp:7:
[build] In file included from ~/GitHub/py-js/source/min-api/script/../include/c74_min.h:10:
[build] In file included from ~/GitHub/py-js/source/min-api/script/../include/c74_min_api.h:393:
[build] ~/GitHub/py-js/source/min-api/script/../include/c74_min_timer.h:126:129: warning: implicit conversion of NULL constant to 'short' [-Wnull-conversion]
[build]                     s_timer_impl_class = max::class_new(timer_impl_name, (max::method)0, (max::method)0, sizeof(timer_impl), 0, NULL);
[build]                                          ~~~                                                                                    ^~~~
[build]                                                                                                                                 0
[build] 1 warning generated.
[build] [100%] Linking CXX CFBundle shared module ../../../../externals/pymx.mxo/Contents/MacOS/pymx
[build] ld: warning: ignoring file ~/GitHub/py-js/source/min-api/max-api/lib/mac/JitterAPI.framework/JitterAPI, missing required architecture arm64 in file ~/GitHub/py-js/source/min-api/max-api/lib/mac/JitterAPI.framework/JitterAPI (2 slices)
[build] Undefined symbols for architecture arm64:
[build]   "_jit_class_addattr", referenced from:
[build]       c74::min::attribute<std::__1::vector<double, std::__1::allocator<double> >, (c74::min::threadsafe)0, c74::min::limit::none, (c74::min::allow_repetitions)2>::create(c74::max::t_class*, void* (*)(void*, ...), void* (*)(void*, ...), bool) in pymx.cpp.o
[build]       c74::min::attribute<std::__1::vector<int, std::__1::allocator<int> >, (c74::min::threadsafe)0, c74::min::limit::none, (c74::min::allow_repetitions)2>::create(c74::max::t_class*, void* (*)(void*, ...), void* (*)(void*, ...), bool) in pymx.cpp.o
[build]       c74::min::attribute<c74::min::symbol, (c74::min::threadsafe)0, c74::min::limit::none, (c74::min::allow_repetitions)2>::create(c74::max::t_class*, void* (*)(void*, ...), void* (*)(void*, ...), bool) in pymx.cpp.o
[build] ld: symbol(s) not found for architecture arm64
[build] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[build] make[2]: *** [../externals/pymx.mxo/Contents/MacOS/pymx] Error 1
[build] make[1]: *** [source/projects/pymx/CMakeFiles/pymx.dir/all] Error 2
[build] make: *** [all] Error 2
[build] Build finished with exit code 2```

**Comment by shakfu** [comment]
Ok, looks like this requires a non-trivial solution as cycling74 seem to have changed their build configuration systems for max-sdk, min-api, etc.  In the case of min-api which is required by the subproject which you are trying to build here, there are even further changes: the sole example now available (https://github.com/Cycling74/min-api/tree/main/examples/min.conan) includes a CMakeLists.txt which itself refers to another cmake-based build system called `conan` (see https://github.com/conan-io/cmake-conan).

This means the old  CMakeLists.txt in pymax is not compatible and needs to be rewritten to use cmake-conan

Unfortunately, I don't have the time to make and test the above changes right now, and will have to revisit the topic of Apple Silicon compatibility when the opportunity arises.

Feel free to try to blend the old CMakeLists.txt and the new one though as this may be easier than it looks.

S

**Comment by shakfu** [comment]
Ok, I've managed to investigate this a bit further. It looks like the external cpp-based compilation infrastructure from Cycling 74 isn't quite fully Apple Silicon compatible yet. (I can't comment on the  c-api max-sdk's status, since I haven't test it yet).

In any cases, for the case at hand, on my new M1 MacBook Air, I failed to compile the demo projects in [https://github.com/Cycling74/min-devkit](https://github.com/Cycling74/min-devkit) which contain `min-api` and `min-lib` and which are the basis for the cpp-based external api which `pymyx` uses. This means the default compile isn't working at all.

I tried the same for `pymx` in this project with updated `min-api` and `min-lib` libraries as well as the latest CMakeLists.txt from the `min-devkit` project and I also was not able to compile.

So it looks like the problem is with Cycling's cpp's SDK. It just isn't working well for Apple Silicon right now.

My advice then is to just wait a bit as these libraries from Cycling74 get some attention and get to work on the new platforms.

**Comment by shakfu** [comment]
I have started a new branch `m1` which aims to provide apple silicon compatibility.

**Comment by wwerk** [comment]
Hi, big up for investigating this issue!
I tried building from the new branch and what I get now is the following linker error:
```
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../externals/py.mxo/Contents/MacOS/py] Error 1
make[1]: *** [source/projects/py/CMakeFiles/py.dir/all] Error 2
make: *** [all] Error 2
~/GitHub/py-js
```

**Comment by shakfu** [comment]
Yup, it's not ready yet for sure. It's developing in fits and spurts so to speak. The challenge in this branch is that there are two goals: achieve Apple Silicon compatibility and converting (completely) to cmake as a build system.

What you have experienced is literally my first attempt to go for broke in my first iteration and hit both goals at the same time. As you can see it didn't quite work 😬 

In addition, you may have noticed that I also departed from the suggested way for macOS by removing Xcode project generation from the compilation chain and trying to do it in cmake alone.

I now realize, of course, that this is a fool's errand, especially in the initial iteration.

Until I get round to another round of 'go-for-broke' development, may I suggest that you try the last step differently and actually follow the [advice](https://github.com/Cycling74/max-sdk/blob/main/README-8.2-update.md) from cycling74, which I will quote hereafter almost verbatim:

```bash
cd ~/py-js
```

Make a directory called build and navigate to that directory

```bash
mkdir build && cd build
```

Build the projects on Mac:

```
cmake -DC74_BUILD_FAT=ON -G Xcode ..
```

Open the generated project files and build in Xcode

**Note**: If you are running on a Mac M1 machine, you will likely see an error cannot be loaded due to system security policy when loading your externals in Max.

To resolve this, you can ad-hoc codesign your external with `codesign --force --deep -s - py.mxo`

**Comment by shakfu** [comment]
Hi @wwerk / @omarcostahamido 

In case you are interested, I have just pushed some final changes which get `py-js` externals to compile successfully on `arm64` machines:

```
py-js % make test
>>> cleaning externals
>>> cleaning support directory
>>> cleaning build directory
>>> running all tests
>>> builder test

running 'make default'
default [######################################################] 100% in 0:00:02
  └-> SUCCESS: 2 out of 2 builds OK


running 'make homebrew-pkg'
homebrew-pkg [#############################] 100% in 0:00:04 - 0:00:00 remaining
  └-> SUCCESS: 2 out of 2 builds OK


running 'make homebrew-ext'
homebrew-ext [#################################################] 100% in 0:00:03
  └-> SUCCESS: 2 out of 2 builds OK


running 'make shared-pkg'
shared-pkg [###############################] 100% in 0:02:08 - 0:00:00 remaining
  └-> SUCCESS: 2 out of 2 builds OK


running 'make shared-ext'
shared-ext [###############################] 100% in 0:02:00 - 0:00:00 remaining
  └-> SUCCESS: 2 out of 2 builds OK


running 'make static-ext'
static-ext [###############################] 100% in 0:02:51 - 0:00:00 remaining
  └-> SUCCESS: 2 out of 2 builds OK


running 'make framework-pkg'
framework-pkg [############################] 100% in 0:02:13 - 0:00:00 remaining
  └-> SUCCESS: 2 out of 2 builds OK


running 'make framework-ext'
framework-ext [#######################     ] 80% in 0:02:04 - 0:00:32 remaining
  └-> SUCCESS: 2 out of 2 builds OK


running 'make relocatable-pkg'
relocatable-pkg [##############            ] 53% in 0:00:19 - 0:00:17 remaining
  └-> SUCCESS: 2 out of 2 builds OK

py-js % arch
arm64
```

I haven't released any `arm64` python3 externals yet but should do shortly.

Before I do, If any of you have an apple silicon machine, can you please git clone the project, `make setup` then `make test` to run the test suite.

Cheers.

**Comment by wwerk** [comment]
Seems to build fine on my M1, nice one!

**Comment by shakfu** [comment]
@wwerk That's great, thanks for testing! 😄

**Comment by wwerk** [comment]
> FYI @wwerk and @omarcostahamido
> 
> Just released a code signed and notarized statically compiled set of [arm64 py-js externals](https://github.com/shakfu/py-js/releases/download/0.1/py-js-v0.1-arm64-py3.9.12-static.zip) in the [0.1 release](https://github.com/shakfu/py-js/releases/0.1).
> 
> These are appropriate for distribution in standalone and Max packages

Seems to be working nicely!
Now time for me to dig through the documentation and figure out importing modules :)
